let shopItemsData = [
  {
    color: "black",
    id: "blackA",
    name: "Casual Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/blackA(1).jpg",
  },
  {
    color: "black",
    id: "blackB",
    name: "Evening Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/blackB(1).jpg",
  },
  {
    color: "blue",
    id: "blueA",
    name: "Office Dress",
    type: "skirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/blueA(1).jpg",
  },
  {
    color: "blue",
    id: "blueB",
    name: "Casual Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/blueB(1).jpg",
  },
  {
    color: "blue",
    id: "blueC",
    name: "Blue Skirt",
    type: "skirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/blueC(1).jpg",
  },
  {
    color: "brown",
    id: "brownA",
    name: "Casual Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/brownA(1).jpg",
  },
  {
    color: "brown",
    id: "brownB",
    name: "Casual Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/brownB(1).jpg",
  },
  {
    color: "brown",
    id: "brownC",
    name: "Gim Suit",
    type: "gimSuit",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/brownC(1).jpg",
  },
  {
    color: "cyan",
    id: "cyanA",
    name: "Party Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/cyanA(1).jpg",
  },
  {
    color: "cyan",
    id: "cyanB",
    name: "Wedding Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/cyanB(1).jpg",
  },
  {
    color: "cyan",
    id: "cyanC",
    name: "Gim Suit",
    type: "gimSuit",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/cyanC(1).jpg",
  },
  {
    color: "green",
    id: "greenA",
    name: "Cocktail Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/greenA(1).jpg",
  },
  {
    color: "green",
    id: "greenB",
    name: "Party Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/greenB(1).jpg",
  },
  {
    color: "grey",
    id: "greyA",
    name: "Gim Suit",
    type: "gimSuit",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/greyA(1).jpg",
  },
  {
    color: "indigo",
    id: "indigoA",
    name: "Floral Skirt",
    type: "skirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/indigoA(1).jpg",
  },
  {
    color: "indigo",
    id: "indigoB",
    name: "Floral Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/indigoB(1).jpg",
  },
  {
    color: "magenta",
    id: "magentaA",
    name: "Magenta Skirt",
    type: "skirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/magentaA(1).jpg",
  },
  {
    color: "orange",
    id: "orangeA",
    name: "Orange Overcoat",
    type: "jacket",
    price: 175,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/orangeA(1).jpg",
  },
  {
    color: "orange",
    id: "orangeB",
    name: "Orange Jacket",
    type: "jacket",
    price: 175,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/orangeB(1).jpg",
  },
  {
    color: "pink",
    id: "pinkA",
    name: "Pink Cocktail",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/pinkA(1).jpg",
  },
  {
    color: "pink",
    id: "pinkB",
    name: "Pink Skirt",
    type: "skirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/pinkB(1).jpg",
  },
  {
    color: "pink",
    id: "pinkC",
    name: "Casual Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/pinkC(1).jpg",
  },
  {
    color: "pink",
    id: "pinkD",
    name: "Gim Suit",
    type: "gimSuit",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/pinkD(1).jpg",
  },
  {
    color: "red",
    id: "redA",
    name: "Evening Dress",
    type: "dress",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/redA(1).jpg",
  },
  {
    color: "red",
    id: "redB",
    name: "Wedding Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/redB(1).jpg",
  },
  {
    color: "red",
    id: "redC",
    name: "Large Skirt",
    type: "skirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/redC(1).jpg",
  },
  {
    color: "red",
    id: "redD",
    name: "Red Skirt",
    type: "skirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/redD(1).jpg",
  },
  {
    color: "red",
    id: "redE",
    name: "Gim Suit",
    type: "gimSuit",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/redE(1).jpg",
  },
  {
    color: "white",
    id: "whiteA",
    name: "Evening Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/whiteA(1).jpg",
  },
  {
    color: "white",
    id: "whiteB",
    name: "Wedding Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/whiteB(1).jpg",
  },
  {
    color: "white",
    id: "whiteC",
    name: "White Skirt",
    type: "skirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/whiteC(1).jpg",
  },
  {
    color: "yellow",
    id: "yellowA",
    name: "Casual Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/yellowA(1).jpg",
  },
  {
    color: "yellow",
    id: "yellowB",
    name: "Wedding Dress",
    type: "dress",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "/imgProducts/yellowB(1).jpg",
  },
];
